import StyledComponentsRegistry, {
  Providers,
} from "@/components/style/themeProvider";
import "./global.css";
import { Inter } from "next/font/google";
import Nav from "@/components/containers/navbar/nav";
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <body className={inter.className}>
          <Providers>
            <Nav />
            {children}
          </Providers>
        </body>
      </StyledComponentsRegistry>
    </html>
  );
}
